# -*- coding: utf-8 -*-
"""CUT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10464U11BbrOzf1Zra5Nyc35VATA6Qmfx
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/taesungp/contrastive-unpaired-translation CUT
# %cd CUT

!pip install -r requirements.txt

!python train.py --dataroot /content/drive/MyDrive/dataset/CUT_dataset/nick_CUT \
                 --name /content/drive/MyDrive/result/nick_CUT_result \
                 --CUT_mode CUT

!python test.py \
  --dataroot /content/drive/MyDrive/dataset/CUT_dataset/front1_nick_rotation1_CUT \
  --name /content/drive/MyDrive/result/front1_nick_CUT_reusult \
  --model cut \
  --num_test 100