# -*- coding: utf-8 -*-
"""resize_images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAELAUn4K-lQvdYIaqWvsmpPVxzHuSYY
"""

# Commented out IPython magic to ensure Python compatibility.
# %cp /content/drive/MyDrive/dataset/atm_dataset /content/drive/MyDrive/dataset/atm_dataset_1024x1024 -r

from PIL import Image
import os

# ✅ 이미지가 저장된 기준 디렉토리
base_dir = '/content/drive/MyDrive/dataset/atm_dataset2'  # 경로 수정

# ✅ 순회하며 .png 파일 리사이즈
for root, _, files in os.walk(base_dir):
    for file in files:
        if file.lower().endswith('.png'):
            file_path = os.path.join(root, file)
            try:
                with Image.open(file_path) as img:
                    resized_img = img.resize((1024, 1024))
                    resized_img.save(file_path)  # 원본 덮어쓰기
                    print(f"✅ 리사이즈 완료: {file_path}")
            except Exception as e:
                print(f"❌ 실패: {file_path} → {e}")