# -*- coding: utf-8 -*-
"""SytleGAN3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4-L1iuigsZ_pGH739GKheOJl91gijjS
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NVlabs/stylegan3.git
# %cd stylegan3

!pip install numpy==1.21.0 click==8.0.1 pillow==8.3.1 scipy==1.7.1 requests==2.26.0 tqdm==4.62.2 ninja==1.10.2 matplotlib==3.4.2
!pip install pyspng

!pip install imageio imageio-ffmpeg==0.4.4

!pip install click requests tqdm pillow numpy scipy ninja opencv-python

"""방법 1: training_loop.py 파일 직접 수정 /content/stylegan3/stylegan3/training/training_loop.py 파일을 찾아서 옵티마이저를 초기화하는 부분을 직접 수정하세요: python# 약 197번째 줄 근처에서 이 코드를 찾으세요 opt = dnnlib.util.construct_class_by_name(params=module.parameters(), **opt_kwargs)

이 코드 위에 다음 코드를 추가하세요
if 'betas' in opt_kwargs: if isinstance(opt_kwargs['betas'], list): opt_kwargs['betas'] = tuple(float(b) for b in opt_kwargs['betas'])
"""

!python train.py --outdir=/content/drive/MyDrive/result/scratch_128x128_StyleGAN3_training-runs \
            --data=/content/drive/MyDrive/dataset/cropped_defects/scratch_128x128 \
            --cfg=stylegan3-t \
            --gpus=1 \
            --batch=32 \
            --gamma=0.5 \
            --batch-gpu=16 \
            --snap=10 \
            --kimg=3200 \
            --metrics=none \
            --resume=/content/drive/MyDrive/result/scratch_128x128_StyleGAN3_training-runs/00000-stylegan3-t-scratch_128x128-gpus1-batch32-gamma0.5/network-snapshot-001800.pkl

!python gen_images.py \
  --outdir=/content/drive/MyDrive/result/scratch_128x128_StyleGAN3_result \
  --trunc=1 \
  --seeds=0-99 \
  --noise-mode=random \
  --network=/content/drive/MyDrive/result/scratch_128x128_StyleGAN3_training-runs/00000-stylegan3-t-scratch_128x128-gpus1-batch32-gamma0.5/network-snapshot-001800.pkl